### ISSUE TITLE
JPA2 Canonical Metamodel isn't populated

### ISSUE THREAD

**Issue by ylemoigne** [BatooOrg/BatooJPA#163]
If I understand right the 6.2.1.1 of the spec, it's not mandatory to implement it, but it's a really usefull part of JPA2 as it allow mostly typesafe query.

**Comment by jinahya** [comment]
Hi. I'm maintaining a [example](https://github.com/jinahya/jpa-metamodels-with-maven-example) generates JPA Metamodels with various providers such as Hibernate, Eclipselink, OpenJPA, DataNucleus.

I'm trying to add Batoo-JPA example.

Can you please guide me with some examples?
